name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    if: github.actor == 'ajmeese7' || github.actor ==  'meese-enterprises'
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - name: Global dependencies
        run: sudo npm install -g gitbook-cli
      - name: Local dependencies
        run: npm install
      - name: Build
        run: gitbook build
      - name: Build dist
        run: |
          mkdir dist
          cp public/*.* dist/
          cp -r _book dist
      - name: Deploy
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.RSYNC_SSH_KEY }}
          ARGS: "-r --delete-after --quiet"
          SERVER_PORT: ${{ secrets.RSYNC_SSH_PORT }}
          FOLDER: "./dist/*"
          SERVER_IP: ${{ secrets.RSYNC_SSH_IP }}
          USERNAME: ${{ secrets.RSYNC_SSH_USERNAME }}
          SERVER_DESTINATION: ${{ secrets.RSYNC_SSH_PATH }}
